
name: Execute SAST

on: push

jobs:
  SAST:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Clone horusec
        run: |
          git clone https://github.com/Fotkurz/horusec.git
      - name: Show files
        run: |
          ls -la
      - name: CD into horusec
        run: |
          cd ./horusec && -ls -la
      - name: Checkout to correct branch
        run: |
          git checkout chore/mute-execution-flag
      - name: Read makefile
        run: |
          cat Makefile
      - name: Build
        run: |
          make build-dev
      - name: Show help
        run: |
          ./horusec start --help
      - name: Run horusec
        run: |
          ./horusec -p=".." -i="**/horusec/**"
      
