
name: Execute SAST

on: push

jobs:
  SAST:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Execute Fork Horusec
        run: |
          git clone https://github.com/Fotkurz/horusec.git && cd horusec && git checkout chore/mute-execution-flag && git pull && make build-dev && ./horusec start -p=".." -i="**/horusec/**
          
