
name: Execute SAST

on: push

jobs:
  SAST:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Clone horusec and checkout to correct branch
        run: |
          git clone https://github.com/Fotkurz/horusec.git && cd horusec && git checkout chore/mute-execution-flag
      - name: Build
        run: |
          make build-dev
      - name: Show help
        run: |
          ./horusec start --help
      - name: Run horusec
        run: |
          ./horusec -p=".." -i="**/horusec/**"
      
