
name: Execute SAST

on: push

jobs:
  SAST:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Clone horusec
        run: |
          git clone https://github.com/Fotkurz/horusec.git && \
          ls -la && \ 
          cd ./horusec && \
          ls -la && \
          git checkout chore/mute-execution-flag \
          cat Makefile && \
          make build-dev && \
          ./horusec start --help && \
          ./horusec -p=".." -i="**/horusec/**"
     
